### ISSUE TITLE
`IllegalArgumentException` on the generation using LLM test generation with JetBrains AI Assistant

### ISSUE THREAD

**Issue by Vladislav0Art** [JetBrains-Research/TestSpark#121]
**Describe the bug**
Once I opened TestSpark modal window, selected LLM as a generator, then selected `AI Assistant JetBrains` **without** modifications of chat model (i.e. leaving `GPT-4`), I received an error (see trace below), however it was not expected.

**To Reproduce**
1. Select LLM as a test generator in the modal window.
2. Select `AI Assistant JetBrains`.
3. Start test generation.
4. See error.

**Expected behavior**
Successful test generation. Seams like the default chat model is set to an empty string, although the `GPT-4` is rendered on UI.

**Stack trace**
```
java.lang.IllegalArgumentException:  is not available option for profile. Available options are: [GPT-4, GPT-4-32k, GPT-4-Turbo, ChatGPT, ChatGPT-16k]
	at org.jetbrains.research.testSpark.grazie.TestGeneration.generate(TestGeneration.kt:31)
	at org.jetbrains.research.grazie.Request$request$1.invokeSuspend(Request.kt:20)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.jetbrains.research.grazie.Request.request(Request.kt:19)
	at org.jetbrains.research.testspark.tools.llm.generation.grazie.GrazieRequestManager.send(GrazieRequestManager.kt:31)
	at org.jetbrains.research.testspark.tools.llm.generation.RequestManager.request(RequestManager.kt:43)
	at org.jetbrains.research.testspark.tools.llm.generation.RequestManager.request$default(RequestManager.kt:30)
	at org.jetbrains.research.testspark.services.LLMChatService.testGenerationRequest(LLMChatService.kt:47)
	at org.jetbrains.research.testspark.tools.llm.generation.LLMProcessManager.runTestGenerator(LLMProcessManager.kt:112)
	at org.jetbrains.research.testspark.tools.Pipeline$runTestGeneration$1.run(Pipeline.kt:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:428)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:478)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:251)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:251)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
<img width="1147" alt="Screenshot 2024-02-16 at 15 49 45" src="https://github.com/JetBrains-Research/TestSpark/assets/47076189/0ca9f4a2-b4f7-409f-a5a1-d5a43433fe45">

**Comment by Vladislav0Art** [comment]
Should this issue be closed now?
