### ISSUE TITLE
[Java+Kotlin] Inner class parsing (incorrect select of a CUT for Java)

### ISSUE THREAD

**Issue by Frosendroska** [JetBrains-Research/TestSpark#256]
## Description

Currently, there is no support of Inner classes.

```java
class MyOuterClass {
    private String name;
    private int age;

    static class MyInnerClass{
        private int sex;

        public int getAge() {
            return sex;
        }
    }
}
```

1. If the cursor is in the empty line inside the inner class, then the testing option is only to test OuterClass.
2. If the cursor is in the non-empty line inside the inner class, then the testing option is the right function, but the class is the OuterClass, not Inner.

**Comment by Vladislav0Art** [comment]
In the above example, if I start the test generation for the method `getAge` I will have the following error:

```
java.lang.NullPointerException
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt$lambda$8(PromptManager.kt:112)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt(PromptManager.kt:70)
	at org.jetbrains.research.testspark.tools.llm.generation.LLMProcessManager.runTestGenerator(LLMProcessManager.kt:105)
	at org.jetbrains.research.testspark.tools.Pipeline$runTestGeneration$1.run(Pipeline.kt:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
``` 
The part of the trace relevant to our code:
```
java.lang.NullPointerException
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt$lambda$8(PromptManager.kt:112)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt(PromptManager.kt:70)
	at org.jetbrains.research.testspark.tools.llm.generation.LLMProcessManager.runTestGenerator(LLMProcessManager.kt:105)
	at org.jetbrains.research.testspark.tools.Pipeline$runTestGeneration$1.run(Pipeline.kt:96)
```

**Reproduction steps:**
1. Start method-based test generation for the method `getAge` of the code snippet above.
2. See the error.

**Explanation**:
The error occurs because we expect the `psiMethod` to always exist:
```kotlin
CodeType.METHOD -> {
   val psiMethod = getPsiMethod(cut, codeType.objectDescription)!! // <- we assert not null
   // ...
```
But the problem in this scenario is we have the `MyOuterClass` as `cut`, not `MyInnerClass`. Therefore, the `psiMethod` is `null` and we fail with `NullPointerException`.

**Solution**: adjust the algorithm for selecting the class under test in Java.


It does not fail for Kotlin but the context for generation is insufficient due to lack of information about the outer class.
