### ISSUE TITLE
[Kotlin] List of kotlin specific bugs (feel free to add)

### ISSUE THREAD

**Issue by Frosendroska** [JetBrains-Research/TestSpark#297]
### 1. `getInterestingPsiClassesWithQualifiedNames` fails when `polyDepthReducing > 0` with the following error

```
java.lang.ClassCastException: class org.jetbrains.kotlin.asJava.classes.KtUltraLightClass cannot be cast to class org.jetbrains.kotlin.psi.KtClass (org.jetbrains.kotlin.asJava.classes.KtUltraLightClass and org.jetbrains.kotlin.psi.KtClass are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @26b09f9f)
```

**Comment by Vladislav0Art** [comment]
This error also occurs when I try to generate unit tests with LLM for `OpenAIRequestManager` class.

**Comment by Vladislav0Art** [comment]
The same issue occurs for `enum classes` (e.g., `JUnitVersion`, `ClassType`, and others). Here is the stack trace log:

```
java.lang.ClassCastException: class org.jetbrains.kotlin.asJava.classes.KtDescriptorBasedFakeLightClass cannot be cast to class org.jetbrains.kotlin.psi.KtClass (org.jetbrains.kotlin.asJava.classes.KtDescriptorBasedFakeLightClass and org.jetbrains.kotlin.psi.KtClass are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @c9c8293)
	at org.jetbrains.research.testspark.kotlin.KotlinPsiClassWrapper.searchSubclasses(KotlinPsiClassWrapper.kt:91)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.getPolymorphismRelationsWithQualifiedNames(PromptManager.kt:228)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt$lambda$6(PromptManager.kt:78)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at org.jetbrains.research.testspark.tools.llm.generation.PromptManager.generatePrompt(PromptManager.kt:65)
	at org.jetbrains.research.testspark.tools.llm.generation.LLMProcessManager.runTestGenerator(LLMProcessManager.kt:106)
	at org.jetbrains.research.testspark.tools.Pipeline$runTestGeneration$1.run(Pipeline.kt:93)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
