### ISSUE TITLE
EvoSuite working directory not found

### ISSUE THREAD

**Issue by Hello-zoka** [JetBrains-Research/TestSpark#401]
**Describe the bug**
Running evosuite for generation, finishes with such error message shown:
```
EvoSuite process error: An exception occurred while executing EvoSuite: Cannot start a process, the working directory '/Users/Iurii.Zaitsev/IdeaProjects/test_java_maven/Users/Iurii.Zaitsev/IdeaProjects/test_java_maven:/Users/Iurii.Zaitsev/IdeaProjects/test_java_maven/target/classes' does not exist. Please verify that you have set a valid path to a Java 11 binary in TestSpark Settings.
```

Full stack trace:
```Kotlin
com.intellij.execution.WorkingDirectoryNotFoundException: Cannot start a process, the working directory '/Users/Iurii.Zaitsev/IdeaProjects/test_java_maven/Users/Iurii.Zaitsev/IdeaProjects/test_java_maven:/Users/Iurii.Zaitsev/IdeaProjects/test_java_maven/target/classes' does not exist
	at com.intellij.execution.configurations.GeneralCommandLine.validateAndPrepareCommandLineForLocalRun(GeneralCommandLine.java:412)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:373)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:85)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at org.jetbrains.research.testspark.tools.evosuite.generation.EvoSuiteProcessManager.runTestGenerator(EvoSuiteProcessManager.kt:148)
	at org.jetbrains.research.testspark.tools.Pipeline$runTestGeneration$1.run(Pipeline.kt:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
```

**To Reproduce**
Run Evosuite generation on the Maven Java project. In my case it was created through the IntelliJ Idea interface.

**Expected behavior**
Successful generation

**Comment by Hello-zoka** [comment]
Not reproducible. Previous occurrence spotted because of project under tests problems
