### ISSUE TITLE
`NullPointerException` occurs for test generation of a line using EvoSuite

### ISSUE THREAD

**Issue by Vladislav0Art** [JetBrains-Research/TestSpark#99]
**Describe the bug**

I tried to generated tests for the following class:
```java
public class Calc {
    public int sum(int a, int b) {
        return a + b; // line 3
    }

    public int multiply(int a, int b) {
        return a * b;
    }
}
```
I launched generation for the line 3 using **EvoSuite** with **DYNOMOSA** and it resulted in the following Exception:
```log
java.lang.NullPointerException
	at org.jetbrains.research.testspark.services.TestsExecutionResultService.getError(TestsExecutionResultService.kt:75)
	at org.jetbrains.research.testspark.display.TestCasePanelFactory.getError(TestCasePanelFactory.kt:547)
	at org.jetbrains.research.testspark.display.TopButtonsPanelFactory.updateTopLabels(TopButtonsPanelFactory.kt:62)
	at org.jetbrains.research.testspark.services.TestCaseDisplayService.displayTestCases(TestCaseDisplayService.kt:147)
	at org.jetbrains.research.testspark.services.ReportLockingService.receiveReport(ReportLockingService.kt:32)
	at org.jetbrains.research.testspark.tools.Display.run$lambda$0(Manager.kt:135)
	// the following entries are internals of intellij openapi:
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
```

**To Reproduce**

1. Copy the class to be tested above.
2. Right click on the line 3 and select TestSpark.
3. Select EvoSuite and the 3rd line for testing.
4. Select DYNOMOSA (**the problem might persist for other algorithms**) and start generation.

**Caution:** not every execution results in this exception. I managed to reproduce it 3/6 times.

**Expected behavior**

Tests for a line should be generated with no errors.

**Screenshots**
![1](https://github.com/JetBrains-Research/TestSpark/assets/47076189/89e7d70a-6018-45d8-904c-088eb9bef10b)
![2](https://github.com/JetBrains-Research/TestSpark/assets/47076189/ee633922-cd33-4aea-b761-ef9aedabf8b9)

![3-1](https://github.com/JetBrains-Research/TestSpark/assets/47076189/be82d2d1-4eb9-4e25-a386-3011fd88b290)
![3-2](https://github.com/JetBrains-Research/TestSpark/assets/47076189/159b29d8-4dae-4142-b280-0c534a9ffe11)

**Additional context**

It might be specific for Windows 10, I did not test it on Unix-based systems.

**Comment by Vladislav0Art** [comment]
Is this one fixed already in some merged PR?

**Comment by arksap2002** [comment]
> Is this one fixed already in some merged PR?

not yet, could you, please, check, if there is still ths bug. I can't perfprm it

**Comment by Vladislav0Art** [comment]
This is the duplicate of #243. I finally found the reproduction steps!
